require("myconf.core.options")
require("myconf.core.keymaps")

require("myconf.plugins.autopairs")
require("myconf.plugins.comment")
require("myconf.plugins.lualine")
require("myconf.plugins.nvim-tree")
require("myconf.plugins.treesitter")
require("myconf.plugins.gitsigns")
require("myconf.plugins.bufferline")
require("myconf.plugins.kanagawa")
require("myconf.plugins.hop")
require("myconf.plugins.toggleterm")
